USE [master]
GO
CREATE DATABASE [sistem2]
GO
ALTER DATABASE [sistem2] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [sistem2] SET ANSI_NULLS ON 
GO
ALTER DATABASE [sistem2] SET ANSI_PADDING ON 
GO
ALTER DATABASE [sistem2] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [sistem2] SET ARITHABORT ON 
GO
ALTER DATABASE [sistem2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [sistem2] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [sistem2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [sistem2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [sistem2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [sistem2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [sistem2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [sistem2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [sistem2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [sistem2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [sistem2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [sistem2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [sistem2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [sistem2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [sistem2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [sistem2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [sistem2] SET  READ_WRITE 
GO
ALTER DATABASE [sistem2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [sistem2] SET  MULTI_USER 
GO
ALTER DATABASE [sistem2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [sistem2] SET DB_CHAINING OFF 