USE [master]
GO
CREATE DATABASE [sistem2_custom]
GO
ALTER DATABASE [sistem2_custom] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [sistem2_custom] SET ANSI_NULLS ON 
GO
ALTER DATABASE [sistem2_custom] SET ANSI_PADDING ON 
GO
ALTER DATABASE [sistem2_custom] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [sistem2_custom] SET ARITHABORT ON 
GO
ALTER DATABASE [sistem2_custom] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [sistem2_custom] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [sistem2_custom] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [sistem2_custom] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [sistem2_custom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [sistem2_custom] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [sistem2_custom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [sistem2_custom] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [sistem2_custom] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [sistem2_custom] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [sistem2_custom] SET  ENABLE_BROKER 
GO
ALTER DATABASE [sistem2_custom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [sistem2_custom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [sistem2_custom] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [sistem2_custom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [sistem2_custom] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [sistem2_custom] SET  READ_WRITE 
GO
ALTER DATABASE [sistem2_custom] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [sistem2_custom] SET  MULTI_USER 
GO
ALTER DATABASE [sistem2_custom] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [sistem2_custom] SET DB_CHAINING OFF 