//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMainWeb {
    using System;
    using System.Web;
    using System.Web.Profile;
    using System.Configuration;
    
    
    public class WebProfile {
        
        private System.Web.Profile.ProfileBase _profileBase;
        
        public WebProfile() {
            this._profileBase = new System.Web.Profile.ProfileBase();
        }
        
        public WebProfile(System.Web.Profile.ProfileBase profileBase) {
            this._profileBase = profileBase;
        }
        
        public virtual int SelectedPageId {
            get {
                return ((int)(this.GetPropertyValue("SelectedPageId")));
            }
            set {
                this.SetPropertyValue("SelectedPageId", value);
            }
        }


        public virtual string DisplayName
        {
            get
            {
                return ((string)(this.GetPropertyValue("DisplayName")));
            }
            set
            {
                this.SetPropertyValue("DisplayName", value);
            }
        }

        public virtual string FirstName
        {
            get
            {
                return ((string)(this.GetPropertyValue("FirstName")));
            }
            set
            {
                this.SetPropertyValue("FirstName", value);
            }
        }

        public virtual string SurName
        {
            get
            {
                return ((string)(this.GetPropertyValue("SurName")));
            }
            set
            {
                this.SetPropertyValue("SurName", value);
            }
        }

        public virtual string Phone
        {
            get
            {
                return ((string)(this.GetPropertyValue("Phone")));
            }
            set
            {
                this.SetPropertyValue("Phone", value);
            }
        }

        public virtual string Address
        {
            get
            {
                return ((string)(this.GetPropertyValue("Address")));
            }
            set
            {
                this.SetPropertyValue("Address", value);
            }
        }
        
        public virtual string SelectedCulture {
            get {
                return ((string)(this.GetPropertyValue("SelectedCulture")));
            }
            set {
                this.SetPropertyValue("SelectedCulture", value);
            }
        }
        
        public virtual string SelectedUICulture {
            get {
                return ((string)(this.GetPropertyValue("SelectedUICulture")));
            }
            set {
                this.SetPropertyValue("SelectedUICulture", value);
            }
        }
        
        public virtual bool EnableDelete {
            get {
                return ((bool)(this.GetPropertyValue("EnableDelete")));
            }
            set {
                this.SetPropertyValue("EnableDelete", value);
            }
        }
        
        public virtual bool UseFCK {
            get {
                return ((bool)(this.GetPropertyValue("UseFCK")));
            }
            set {
                this.SetPropertyValue("UseFCK", value);
            }
        }
        
        public virtual bool AutoPublish {
            get {
                return ((bool)(this.GetPropertyValue("AutoPublish")));
            }
            set {
                this.SetPropertyValue("AutoPublish", value);
            }
        }
        
        public virtual bool ExpandTree {
            get {
                return ((bool)(this.GetPropertyValue("ExpandTree")));
            }
            set {
                this.SetPropertyValue("ExpandTree", value);
            }
        }
        
        public virtual bool EnableStructureEditing {
            get {
                return ((bool)(this.GetPropertyValue("EnableStructureEditing")));
            }
            set {
                this.SetPropertyValue("EnableStructureEditing", value);
            }
        }
        
        public virtual int SelectedCultureId {
            get {
                return ((int)(this.GetPropertyValue("SelectedCultureId")));
            }
            set {
                this.SetPropertyValue("SelectedCultureId", value);
            }
        }
        
        public virtual int SelectedUICultureId {
            get {
                return ((int)(this.GetPropertyValue("SelectedUICultureId")));
            }
            set {
                this.SetPropertyValue("SelectedUICultureId", value);
            }
        }
        
        public virtual int SelectedWebSiteId {
            get {
                return ((int)(this.GetPropertyValue("SelectedWebSiteId")));
            }
            set {
                this.SetPropertyValue("SelectedWebSiteId", value);
            }
        }
        
        public virtual int RootNodeId {
            get {
                return ((int)(this.GetPropertyValue("RootNodeId")));
            }
            set {
                this.SetPropertyValue("RootNodeId", value);
            }
        }
        
        public virtual bool ShowMenuGroupIds {
            get {
                return ((bool)(this.GetPropertyValue("ShowMenuGroupIds")));
            }
            set {
                this.SetPropertyValue("ShowMenuGroupIds", value);
            }
        }
		
        public virtual bool ShowUntranslated {
            get {
                return ((bool)(this.GetPropertyValue("ShowUntranslated")));
            }
            set {
                this.SetPropertyValue("ShowUntranslated", value);
            }
        }

        public virtual string UserSecret
        {
            get
            {
                return ((string)(this.GetPropertyValue("UserSecret")));
            }
            set
            {
                this.SetPropertyValue("UserSecret", value);
            }
        }
        
        public static WebProfile Current {
            get {
                return new WebProfile(System.Web.HttpContext.Current.Profile);
            }
        }
        
        public virtual System.Web.Profile.ProfileBase ProfileBase {
            get {
                return this._profileBase;
            }
        }
        
        public virtual object this[string propertyName] {
            get {
                return this._profileBase[propertyName];
            }
            set {
                this._profileBase[propertyName] = value;
            }
        }
        
        public virtual string UserName {
            get {
                return this._profileBase.UserName;
            }
        }
        
        public virtual bool IsAnonymous {
            get {
                return this._profileBase.IsAnonymous;
            }
        }
        
        public virtual bool IsDirty {
            get {
                return this._profileBase.IsDirty;
            }
        }
        
        public virtual System.DateTime LastActivityDate {
            get {
                return this._profileBase.LastActivityDate;
            }
        }
        
        public virtual System.DateTime LastUpdatedDate {
            get {
                return this._profileBase.LastUpdatedDate;
            }
        }
        
        public virtual System.Configuration.SettingsProviderCollection Providers {
            get {
                return this._profileBase.Providers;
            }
        }
        
        public virtual System.Configuration.SettingsPropertyValueCollection PropertyValues {
            get {
                return this._profileBase.PropertyValues;
            }
        }
        
        public virtual System.Configuration.SettingsContext Context {
            get {
                return this._profileBase.Context;
            }
        }
        
        public virtual bool IsSynchronized {
            get {
                return this._profileBase.IsSynchronized;
            }
        }
        
        public static System.Configuration.SettingsPropertyCollection Properties {
            get {
                return System.Web.Profile.ProfileBase.Properties;
            }
        }
        
        public virtual WebProfile GetProfile(string username) {
            return new WebProfile(System.Web.Profile.ProfileBase.Create(username));
        }
        
        public virtual object GetPropertyValue(string propertyName) {
            return this._profileBase.GetPropertyValue(propertyName);
        }
        
        public virtual void SetPropertyValue(string propertyName, object propertyValue) {
            this._profileBase.SetPropertyValue(propertyName, propertyValue);
        }
        
        public virtual System.Web.Profile.ProfileGroupBase GetProfileGroup(string groupName) {
            return this._profileBase.GetProfileGroup(groupName);
        }
        
        public virtual void Initialize(string username, bool isAuthenticated) {
            this._profileBase.Initialize(username, isAuthenticated);
        }
        
        public virtual void Save() {
            this._profileBase.Save();
        }
        
        public virtual void Initialize(System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection properties, System.Configuration.SettingsProviderCollection providers) {
            this._profileBase.Initialize(context, properties, providers);
        }
        
        public static System.Configuration.SettingsBase Synchronized(System.Configuration.SettingsBase settingsBase) {
            return System.Web.Profile.ProfileBase.Synchronized(settingsBase);
        }
        
        public static System.Web.Profile.ProfileBase Create(string userName) {
            return System.Web.Profile.ProfileBase.Create(userName);
        }
        
        public static System.Web.Profile.ProfileBase Create(string userName, bool isAuthenticated) {
            return System.Web.Profile.ProfileBase.Create(userName, isAuthenticated);
        }
    }
}
